---
  - name: Update apt
    sudo: yes
    apt: update_cache=yes

  - name: Install initial packages
    sudo: yes
    apt: pkg={{ item }} state=latest
    with_items:
    - curl
    - wget
    - git
    - ruby
    - python-software-properties
    - python-selinux
    - python-pip
    - build-essential
    - libssl-dev
    - vim
    - tmux
    - tree
    - mc
    - htop
    #- fail2ban

#  - name: Update apt
#    sudo: yes
#    apt: update_cache=yes