---
### Install required applications
- include: init.yml
- include: marinadb.yml
- include: nginx.yml
- include: php55.yml
- include: nodejs.yml
  tags:
    - node
- include: composer.yml
- include: wp-cli.yml
- include: bundler.yml
- include: memcached.yml
- include: dev_tools.yml
  tags:
    - dev_tools




### TODO: use nvm to install/manage nodejs
#- include: nvm.yml
#  tags:
#    - nvm
#  sudo: no
