---
- include_vars: ./app-versions.yml

- name: Get NVM
  sudo: true
  sudo_user: "{{ deploy_user }}"
  git: repo=https://github.com/creationix/nvm.git version={{ version.nvm }} dest=~/.nvm
  register: nvm

- name: Install NVM
  command: sh ~/.nvm/install.sh
  sudo: false


#### using .nvmrc file to set in project directory
#- name: Install 10.0.32
#  shell: nvm install 10.0.32
#  register: nvm_install_result
#
#
#- name: Check if {{ version.nodejs }} is the default node version
#  shell: sudo -iu {{ deploy_user }} nvm ls | grep -e 'default -> {{ version.nodejs }}'
#  register: nvm_check_default
#  changed_when: false
#  ignore_errors: true
#
#- name: Set default node version to {{ version.nodejs }}
#  command: sudo -iu {{ deploy_user }} nvm alias default {{ version.nodejs }}
#  when: nvm_check_default | failed

