# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.box = "cmad/trusty-server64" #download box from vagrant cloud: org/boxname
    config.vm.provider "virtualbox" do |vb|
    vb.gui = true   
  end
    config.vm.provider "vmware_workstation" do |vmware|
    vmware.gui = true
  end

end